In [19]:
import pandas as pd
import requests

df = pd.read_csv('boliga_all.csv')

api_addresses = [' '.join([a.split(',')[0], z]) for a, z in df[['address', 'zip_code']].values]

df

,address,zip_code,price,sell_date,sell_type,price_per_sq_m,no_rooms,housing_type,size_in_sq_m,year_of_construction,price_change_in_pct
0,"Ved Volden 5, 5. TV",1425 København K,4000000,23-05-2017,Alm. Salg,43956.0,3.0,Lejlighed,91.0,1938.0,0.0
1,"Rådhusstræde 4C, 1",1466 København K,4895000,18-05-2017,Alm. Salg,46619.0,3.0,Lejlighed,105.0,1796.0,0.0
2,"Store Kongensgade 112A, 3",1264 København K,250000,15-05-2017,Andet,1851.0,2.0,Lejlighed,135.0,1860.0,0.0
3,"Amaliegade 13G, 2",1256 København K,7375000,15-05-2017,Alm. Salg,75255.0,3.0,Lejlighed,98.0,1948.0,9.0
4,"Borgergade 144, 3. TH",1300 København K,5825000,10-05-2017,Alm. Salg,57673.0,3.0,Lejlighed,101.0,1854.0,3.0
5,"Nørre Søgade 9A, 1. TH",1370 København K,1126250,10-05-2017,Fam. Salg,10525.0,3.0,Lejlighed,107.0,1882.0,0.0
6,"Wildersgade 22, ST",1408 København K,1556700,09-05-2017,Alm. Salg,17689.0,3.0,Lejlighed,88.0,1858.0,0.0
7,"Toldbodgade 10A, 1",1253 København K,3750000,08-05-2017,Fam. Salg,20380.0,5.0,Lejlighed,184.0,1862.0,0.0
8,"Andreas Bjørns Gade 4, 3. TH",1428 København K,1700000,05-05-2017,Alm. Salg,31481.0,2.0,Lejlighed,54.0,1901.0,0.0
9,"Sølvgade 15, 4. TH",1307 København K,4215000,04-05-2017,Alm. Salg,52037.0,3.0,Lejlighed,81.0,1957.0,-2.0
10,"Linnésgade 16A, 1",1361 København K,6300000,04-05-2017,Alm. Salg,40645.0,5.0,Lejlighed,155.0,1880.0,0.0
11,"Store Kongensgade 63A, ST. 4",1264 København K,1780000,03-05-2017,Fam. Salg,18163.0,3.0,Lejlighed,98.0,1932.0,0.0
12,"Peder Skrams Gade 28, 2. TV",1054 København K,4080000,03-05-2017,Alm. Salg,53684.0,3.0,Lejlighed,76.0,1870.0,0.0
13,"Brobergsgade 14, 1. TV",1427 København K,2750000,02-05-2017,Alm. Salg,55000.0,2.0,Lejlighed,50.0,1902.0,-8.0
14,"Sølvgade 13, 2. TV",1307 København K,3150000,01-05-2017,Alm. Salg,43150.0,3.0,Lejlighed,73.0,1957.0,0.0
15,"Ny Adelgade 9, 2. TH",1104 København K,1950000,01-05-2017,Alm. Salg,27857.0,3.0,Lejlighed,70.0,1800.0,-44.0
16,"Lavendelstræde 9, 2. TV",1462 København K,1550000,01-05-2017,Alm. Salg,23484.0,2.0,Lejlighed,66.0,1799.0,0.0
17,"Åbenrå 10, 2. 5",1124 København K,1650000,01-05-2017,Alm. Salg,23571.0,2.0,Lejlighed,70.0,1972.0,0.0
18,"Grønnegade 31, 3. TV",1107 København K,1200000,01-05-2017,Alm. Salg,24489.0,2.0,Lejlighed,49.0,1741.0,0.0
19,"Badstuestræde 16, 2",1209 København K,2700000,01-05-2017,Alm. Salg,27835.0,4.0,Lejlighed,97.0,1797.0,0.0
20,"Nørre Voldgade 70, 4",1358 København K,1870000,28-04-2017,Fam. Salg,18888.0,4.0,Lejlighed,99.0,1677.0,0.0
21,"Fredericiagade 25, 5. 1",1310 København K,3150000,27-04-2017,Alm. Salg,26694.0,3.0,Lejlighed,118.0,1968.0,0.0
22,"Sølvgade 19, 2. MF",1307 København K,2425000,27-04-2017,Alm. Salg,49489.0,2.0,Lejlighed,49.0,1806.0,-3.0
23,"David Balfours Gade 3, ST. TV",1402 København K,3100000,27-04-2017,Alm. Salg,37349.0,2.0,Lejlighed,83.0,2002.0,0.0
24,"Vimmelskaftet 36A, 3. TH",1161 København K,3695000,27-04-2017,Alm. Salg,43988.0,3.0,Lejlighed,84.0,1857.0,-3.0
25,"Store Kongensgade 110C, 3. TV",1264 København K,3050000,27-04-2017,Fam. Salg,25847.0,3.0,Lejlighed,118.0,1838.0,0.0
26,"Andreas Bjørns Gade 10, 3. TV",1428 København K,2367000,26-04-2017,Alm. Salg,44660.0,2.0,Lejlighed,53.0,1901.0,0.0
27,"Grønnegade 31, 4",1107 København K,3950000,26-04-2017,Alm. Salg,54109.0,2.0,Lejlighed,73.0,1741.0,0.0
28,"Peder Skrams Gade 27, 3. TH",1054 København K,6250000,26-04-2017,Alm. Salg,55803.0,4.0,Lejlighed,112.0,1900.0,0.0
29,"Andreas Bjørns Gade 22, 3. TH",1428 København K,2900000,25-04-2017,Alm. Salg,52727.0,2.0,Lejlighed,55.0,1901.0,-3.0
...,...,...,...,...,...,...,...,...,...,...,...
1385279,Chr. Xs Vej 79,9990 Skagen,520000,14-04-1992,Alm. Salg,NaN,4.0,Villa,86.0,1943.0,0.0
1385280,Østre Strandvej 93,9990 Skagen,715000,02-04-1992,Fam. Salg,NaN,6.0,Villa,161.0,1978.0,0.0
1385281,Rylevej 2,9990 Skagen,520000,26-03-1992,Fam. Salg,4444.0,5.0,Villa,117.0,1978.0,0.0
1385282,Jens Winthers Vej 17,9990 Skagen,409000,24-03-1992,Alm. Salg,3970.0,4.0,Villa,103.0,1950.0,0.0
1385283,Sønderklit 38,9990 Skagen,525000,23-03-1992,Fam. Salg,NaN,5.0,Villa,144.0,1974.0,0.0
1385284,Fabriciusvej 3,9990 Skagen,550000,20-03-1992,Alm. Salg,5555.0,3.0,Villa,99.0,1945.0,0.0
1385285,Skagbanke 35,9990 Skagen,900000,19-03-1992,Fam. Salg,5000.0,6.0,Villa,180.0,1977.0,0.0
1385286,Vesterled 4,9990 Skagen,400000,17-03-1992,Fam. Salg,3809.0,4.0,Villa,105.0,1880.0,0.0
1385287,Ydunsvej 19,9990 Skagen,1030000,17-03-1992,Alm. Salg,NaN,7.0,Villa,187.0,1979.0,0.0
1385288,Fiskerbanke 23,9990 Skagen,545273,12-03-1992,Alm. Salg,3473.0,5.0,Villa,157.0,1978.0,0.0
1385289,Redningsvej 58,9990 Skagen,1100000,09-03-1992,Alm. Salg,11458.0,4.0,Sommerhus,96.0,1993.0,0.0
1385290,Oddevej 23,9990 Skagen,550000,06-03-1992,Alm. Salg,NaN,5.0,Villa,204.0,1931.0,0.0
1385291,Sct. Laurentii Vej 121,9990 Skagen,342474,04-03-1992,Alm. Salg,3171.0,3.0,Lejlighed,108.0,1900.0,0.0
1385292,Østre Strandvej 35A,9990 Skagen,625000,03-03-1992,Alm. Salg,4807.0,4.0,Villa,130.0,1958.0,0.0
1385293,Skarpæsvej 8,9990 Skagen,510000,26-02-1992,Alm. Salg,3469.0,4.0,Villa,147.0,1954.0,0.0
1385294,Ryttervej 36,9990 Skagen,960000,24-02-1992,Alm. Salg,6400.0,5.0,Villa,150.0,1986.0,0.0
1385295,Doggerbanke 74,9990 Skagen,514000,20-02-1992,Alm. Salg,3893.0,5.0,Villa,132.0,1980.0,0.0
1385296,Doggerbanke 15,9990 Skagen,620000,18-02-1992,Alm. Salg,4806.0,6.0,Villa,129.0,1980.0,0.0
1385297,Dr. Alexandrines Vej 52,9990 Skagen,585000,14-02-1992,Alm. Salg,5223.0,5.0,Villa,112.0,1941.0,0.0
1385298,Ankermedet 51,9990 Skagen,425000,14-02-1992,Alm. Salg,3148.0,5.0,Villa,135.0,1958.0,0.0
1385299,Kæruldvej 39,9990 Skagen,135745,06-02-1992,Fam. Salg,1525.0,4.0,Sommerhus,89.0,1992.0,0.0
1385300,Spliidsvej 39,9990 Skagen,465000,01-02-1992,Fam. Salg,3100.0,6.0,Villa,150.0,1970.0,0.0
1385301,Østerled 1,9990 Skagen,391000,30-01-1992,Fam. Salg,2572.0,5.0,Rækkehus,152.0,1933.0,0.0
1385302,Nedre Mosevej 7,9990 Skagen,575000,21-01-1992,Alm. Salg,NaN,5.0,Villa,125.0,1970.0,0.0
1385303,Karredvænget 6,9990 Skagen,150000,21-01-1992,Alm. Salg,1685.0,5.0,Sommerhus,89.0,1995.0,0.0
1385304,Tranevej 68A,9990 Skagen,225000,15-01-1992,Alm. Salg,1785.0,5.0,Sommerhus,126.0,1993.0,0.0
1385305,Middelbanke 29,9990 Skagen,545000,14-01-1992,Fam. Salg,5093.0,4.0,Villa,107.0,1974.0,0.0
1385306,"Chr. Xs Vej 51, 1",9990 Skagen,3600000,14-01-1992,Alm. Salg,24000.0,5.0,Anden beboelse,150.0,1965.0,0.0
1385307,Høgenhaug 5,9990 Skagen,500000,08-01-1992,Fam. Salg,4310.0,5.0,Villa,116.0,1977.0,0.0
1385308,Krøyersvej 12B,9990 Skagen,69250,08-01-1992,Alm. Salg,814.0,3.0,Villa,85.0,1911.0,0.0

In [20]:

def get_location_for(address='Copenhagen'):
    api_url = 'https://maps.googleapis.com/maps/api/geocode/json'
    
    try:
        r = requests.get(api_url, params={'sensor': 'false', 
                                          'address': address})
        results = r.json()['results']
    
        location = results[0]['geometry']['location']
        lat, lon = location['lat'], location['lng']
    except:
        lat, lon = None, None
    return lat, lon

In [28]:
df_cphn_2000 = df[(df['zip_code'] == '2200 København N')]

complete_addresses = [' '.join([a.split(',')[0], z]) 
                      for a, z in df_cphn_2000[['address', 'zip_code']].values]
# This line is the equivalent of the older
df_cphn_2000 = df_cphn_2000.assign(complete_addresses=complete_addresses)
# df_cphn_2000.loc[:, 'complete_addresses'] = complete_addresses
# df_cphn_2000['complete_addresses'] = complete_addresses, which will produce a warning

,address,zip_code,price,sell_date,sell_type,price_per_sq_m,no_rooms,housing_type,size_in_sq_m,year_of_construction,price_change_in_pct,complete_addresses
87618,"Schleppegrellsgade 10, ST. TV",2200 København N,4395000,24-05-2017,Alm. Salg,47771.0,4.0,Lejlighed,92.0,1892.0,0.0,Schleppegrellsgade 10 2200 København N
87619,"Blågårdsgade 26, 3. 23",2200 København N,1160000,23-05-2017,Fam. Salg,19661.0,1.0,Lejlighed,59.0,1972.0,0.0,Blågårdsgade 26 2200 København N
87620,"Sortedam Dossering 41D, 4. TV",2200 København N,2000000,22-05-2017,Fam. Salg,33333.0,2.0,Lejlighed,60.0,1963.0,0.0,Sortedam Dossering 41D 2200 København N
87621,"Gormsgade 6, 1. 6",2200 København N,1357000,19-05-2017,Fam. Salg,15779.0,3.0,Lejlighed,86.0,1965.0,0.0,Gormsgade 6 2200 København N
87622,"Egegade 10, 5. TV",2200 København N,1318000,17-05-2017,Fam. Salg,25346.0,2.0,Lejlighed,52.0,1893.0,0.0,Egegade 10 2200 København N
87623,"Rådmandsgade 40B, 4. TH",2200 København N,1825000,17-05-2017,Alm. Salg,33796.0,2.0,Lejlighed,54.0,1899.0,-4.0,Rådmandsgade 40B 2200 København N
87624,"Bjelkes Allé 37, 1",2200 København N,2380000,09-05-2017,Alm. Salg,14512.0,6.0,Lejlighed,164.0,1884.0,0.0,Bjelkes Allé 37 2200 København N
87625,"Sandbjerggade 54, 2. TH",2200 København N,1725000,07-05-2017,Alm. Salg,39204.0,2.0,Lejlighed,44.0,1935.0,-7.0,Sandbjerggade 54 2200 København N
87626,"Rådmandsgade 40C, 1. 83",2200 København N,561000,05-05-2017,Fam. Salg,12750.0,1.0,Lejlighed,44.0,1967.0,0.0,Rådmandsgade 40C 2200 København N
87627,"Poppelgade 1, 1. TH",2200 København N,1860000,04-05-2017,Alm. Salg,41333.0,2.0,Lejlighed,45.0,1886.0,-7.0,Poppelgade 1 2200 København N
87628,"Baldersgade 39, 1. TH",2200 København N,3900000,03-05-2017,Alm. Salg,43333.0,4.0,Lejlighed,90.0,1906.0,-2.0,Baldersgade 39 2200 København N
87629,"Birkegade 15, 3. TH",2200 København N,1437500,03-05-2017,Fam. Salg,27644.0,2.0,Lejlighed,52.0,1892.0,0.0,Birkegade 15 2200 København N
87630,"Vølundsgade 22, 4. TV",2200 København N,1900000,02-05-2017,Alm. Salg,32758.0,2.0,Lejlighed,58.0,1907.0,0.0,Vølundsgade 22 2200 København N
87631,"Krogerupgade 51, 2. TH",2200 København N,1046532,01-05-2017,Fam. Salg,19745.0,2.0,Lejlighed,53.0,1935.0,0.0,Krogerupgade 51 2200 København N
87632,"Sigynsgade 44, ST. TV",2200 København N,892500,01-05-2017,Fam. Salg,14875.0,1.0,Lejlighed,60.0,1991.0,0.0,Sigynsgade 44 2200 København N
87633,"Tagensvej 56, 3. TH",2200 København N,1440000,27-04-2017,Fam. Salg,21176.0,3.0,Lejlighed,68.0,1933.0,0.0,Tagensvej 56 2200 København N
87634,"Kronborggade 8, 2. TH",2200 København N,3500000,27-04-2017,Alm. Salg,50000.0,3.0,Lejlighed,70.0,1899.0,-5.0,Kronborggade 8 2200 København N
87635,"Hamletsgade 8, 3. 119",2200 København N,1935000,26-04-2017,Alm. Salg,29769.0,2.0,Lejlighed,65.0,1975.0,-3.0,Hamletsgade 8 2200 København N
87636,"Møllegade 34, 4. TV",2200 København N,1700000,26-04-2017,Fam. Salg,21518.0,3.0,Lejlighed,79.0,1901.0,0.0,Møllegade 34 2200 København N
87637,"Hamletsgade 30, ST. TV",2200 København N,2100000,25-04-2017,Alm. Salg,21875.0,3.0,Lejlighed,96.0,1938.0,-8.0,Hamletsgade 30 2200 København N
87638,"Heimdalsgade 42, 2. 21",2200 København N,1365000,25-04-2017,Alm. Salg,27300.0,1.0,Lejlighed,50.0,1975.0,-2.0,Heimdalsgade 42 2200 København N
87639,"Peblinge Dossering 20, 1. TH",2200 København N,1657500,25-04-2017,Fam. Salg,23345.0,3.0,Lejlighed,71.0,1886.0,0.0,Peblinge Dossering 20 2200 København N
87640,"Griffenfeldsgade 43, 3",2200 København N,3710000,23-04-2017,Alm. Salg,31982.0,3.0,Lejlighed,116.0,1880.0,3.0,Griffenfeldsgade 43 2200 København N
87641,"Lundtoftegade 84, 4. TH",2200 København N,3250000,23-04-2017,Alm. Salg,37790.0,3.0,Lejlighed,86.0,1907.0,-6.0,Lundtoftegade 84 2200 København N
87642,"Peter Fabers Gade 36, 5. TV",2200 København N,900000,23-04-2017,Fam. Salg,21428.0,2.0,Lejlighed,42.0,1883.0,0.0,Peter Fabers Gade 36 2200 København N
87643,"Heimdalsgade 42, 3. 30",2200 København N,605000,21-04-2017,Andet,12604.0,1.0,Lejlighed,48.0,1975.0,0.0,Heimdalsgade 42 2200 København N
87644,"Uffesgade 10, ST. TH",2200 København N,1875000,21-04-2017,Alm. Salg,35377.0,2.0,Lejlighed,53.0,1901.0,-3.0,Uffesgade 10 2200 København N
87645,"Rådmandsgade 40C, 4. 127",2200 København N,1207000,21-04-2017,Fam. Salg,17242.0,3.0,Lejlighed,70.0,1967.0,0.0,Rådmandsgade 40C 2200 København N
87646,"Egegade 2, 2. TH",2200 København N,257500,20-04-2017,Fam. Salg,3301.0,3.0,Lejlighed,78.0,1884.0,0.0,Egegade 2 2200 København N
87647,"Rådmandsgade 40C, ST. 80",2200 København N,2350000,19-04-2017,Alm. Salg,31756.0,3.0,Lejlighed,74.0,1967.0,0.0,Rådmandsgade 40C 2200 København N
...,...,...,...,...,...,...,...,...,...,...,...,...
146183,"Bjelkes Allé 4, 2. 7",2200 København N,170000,26-04-1993,Alm. Salg,2881.0,1.0,Lejlighed,59.0,1970.0,0.0,Bjelkes Allé 4 2200 København N
146184,"Rantzausgade 11, 7. 37",2200 København N,759800,21-04-1993,Alm. Salg,5935.0,4.0,Lejlighed,128.0,1970.0,0.0,Rantzausgade 11 2200 København N
146185,"Hamletsgade 4, 1. 143",2200 København N,310000,19-04-1993,Alm. Salg,4366.0,2.0,Lejlighed,71.0,1975.0,0.0,Hamletsgade 4 2200 København N
146186,"Rådmandsgade 56, 1",2200 København N,950000,17-03-1993,Alm. Salg,14393.0,4.0,Lejlighed,66.0,1930.0,0.0,Rådmandsgade 56 2200 København N
146187,"Fenrisgade 1, 5. TV",2200 København N,309350,22-02-1993,Alm. Salg,4833.0,2.0,Lejlighed,64.0,1934.0,0.0,Fenrisgade 1 2200 København N
146188,"Peblinge Dossering 28, 3. TV",2200 København N,690000,15-02-1993,Alm. Salg,8414.0,3.0,Lejlighed,82.0,1880.0,0.0,Peblinge Dossering 28 2200 København N
146189,"Ægirsgade 18, 3. TV",2200 København N,320000,11-01-1993,Alm. Salg,5079.0,2.0,Lejlighed,63.0,1903.0,0.0,Ægirsgade 18 2200 København N
146190,"Ægirsgade 68, 1. TV",2200 København N,172500,05-01-1993,Alm. Salg,NaN,2.0,Lejlighed,58.0,1902.0,0.0,Ægirsgade 68 2200 København N
146191,"Julius Bloms Gade 6, 5. 8",2200 København N,50000,09-12-1992,Alm. Salg,1851.0,1.0,Lejlighed,27.0,1908.0,0.0,Julius Bloms Gade 6 2200 København N
146192,"Sankt Hans Gade 4A, 5. TH",2200 København N,567000,07-12-1992,Alm. Salg,8859.0,2.0,Lejlighed,64.0,1893.0,0.0,Sankt Hans Gade 4A 2200 København N
146193,"Hamletsgade 17, 3. TV",2200 København N,330000,04-11-1992,Alm. Salg,5789.0,2.0,Lejlighed,57.0,1947.0,0.0,Hamletsgade 17 2200 København N
146194,"Læssøesgade 25, 1. TH",2200 København N,276049,03-10-1992,Alm. Salg,2244.0,4.0,Lejlighed,123.0,1868.0,0.0,Læssøesgade 25 2200 København N
146195,"Åboulevard 60, 3. TH",2200 København N,533450,01-10-1992,Alm. Salg,3441.0,6.0,Lejlighed,155.0,1903.0,0.0,Åboulevard 60 2200 København N
146196,"Rådmandsgade 46A, 2. TH",2200 København N,435000,25-08-1992,Alm. Salg,4027.0,4.0,Lejlighed,108.0,1933.0,0.0,Rådmandsgade 46A 2200 København N
146197,"Nørrebrogade 229, 4. TH",2200 København N,150000,12-08-1992,Alm. Salg,NaN,3.0,Lejlighed,58.0,1896.0,0.0,Nørrebrogade 229 2200 København N
146198,"Holtegade 12, 4. TV",2200 København N,324220,15-07-1992,Alm. Salg,4631.0,2.0,Lejlighed,70.0,1932.0,0.0,Holtegade 12 2200 København N
146199,"Sankt Hans Gade 28, 3",2200 København N,559990,14-07-1992,Alm. Salg,5490.0,4.0,Lejlighed,102.0,1883.0,0.0,Sankt Hans Gade 28 2200 København N
146200,"Husumgade 10, ST. TV",2200 København N,142500,09-07-1992,Alm. Salg,1759.0,3.0,Lejlighed,81.0,1904.0,0.0,Husumgade 10 2200 København N
146201,"Ravnsborg Tværgade 2, 3",2200 København N,445400,22-06-1992,Alm. Salg,4454.0,3.0,Lejlighed,100.0,1869.0,0.0,Ravnsborg Tværgade 2 2200 København N
146202,"Griffenfeldsgade 43, ST",2200 København N,22000,30-05-1992,Fam. Salg,159.0,4.0,Lejlighed,138.0,1880.0,0.0,Griffenfeldsgade 43 2200 København N
146203,"Nørre Allé 11A, ST. TV",2200 København N,390000,26-05-1992,Alm. Salg,5064.0,2.0,Lejlighed,77.0,1900.0,0.0,Nørre Allé 11A 2200 København N
146204,"Korsgade 24, 5. TV",2200 København N,325000,12-05-1992,Alm. Salg,4850.0,3.0,Lejlighed,67.0,1872.0,0.0,Korsgade 24 2200 København N
146205,"Lundtoftegade 95, ST. TH",2200 København N,245000,11-05-1992,Alm. Salg,6447.0,3.0,Detailhandel,38.0,1930.0,0.0,Lundtoftegade 95 2200 København N
146206,"Florsgade 7, 4. TH",2200 København N,570300,30-04-1992,Alm. Salg,5940.0,3.0,Lejlighed,96.0,1905.0,0.0,Florsgade 7 2200 København N
146207,"Griffenfeldsgade 8, 5. TH",2200 København N,640000,02-04-1992,Alm. Salg,5925.0,5.0,Lejlighed,108.0,1890.0,0.0,Griffenfeldsgade 8 2200 København N
146208,"Hamletsgade 28, 4. TH",2200 København N,294600,30-03-1992,Alm. Salg,5356.0,2.0,Lejlighed,55.0,1938.0,0.0,Hamletsgade 28 2200 København N
146209,"Husumgade 12, 3. TH",2200 København N,398000,11-03-1992,Alm. Salg,5168.0,3.0,Lejlighed,77.0,1904.0,0.0,Husumgade 12 2200 København N
146210,"Husumgade 10, 4. TH",2200 København N,435000,16-02-1992,Alm. Salg,5178.0,3.0,Lejlighed,84.0,1904.0,0.0,Husumgade 10 2200 København N
146211,"Nørrebrogade 229, 3. TV",2200 København N,272698,16-01-1992,Alm. Salg,NaN,2.0,Lejlighed,50.0,1896.0,0.0,Nørrebrogade 229 2200 København N
146212,"Peter Fabers Gade 41, 2. TH",2200 København N,250000,04-01-1992,Alm. Salg,5000.0,2.0,Lejlighed,50.0,1895.0,0.0,Peter Fabers Gade 41 2200 København N

In [30]:
to_code_addresses = df_cphn_2000['complete_addresses'].unique()
locations = [get_location_for(a) for a in to_code_addresses]
locations

[(None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None),
 (None, None)]

In [31]:
lats, lons = zip(*locations)

geocoded = pd.DataFrame({'complete_addresses': to_code_addresses,
                         'lat': lats,
                         'lon': lons})
geocoded.head()

                        complete_addresses   lat   lon
0   Schleppegrellsgade 10 2200 København N  None  None
1         Blågårdsgade 26 2200 København N  None  None
2  Sortedam Dossering 41D 2200 København N  None  None
3             Gormsgade 6 2200 København N  None  None
4              Egegade 10 2200 København N  None  None

In [ ]:
from osmread import parse_file, Node


def decode_node_to_csv():
    for entry in parse_file('denmark-latest.osm'):
        if (isinstance(entry, Node) and 
            'addr:street' in entry.tags and 
            'addr:postcode' in entry.tags and 
            'addr:housenumber' in entry.tags):

            yield entry


for idx, decoded_node in enumerate(decode_node_to_csv()):
    if idx > 100:
        break
    print(idx, decoded_node)